### ISSUE TITLE
Encountered an error (Error: undefined:1:9: property missing ':')

### ISSUE THREAD

**Issue by techvlad** [jarvis394/habra#129] opened 2021-08-31 06:55 UTC
### Describe the problem:

[Link to broken article](https://habra.vercel.app/company/citymobil/blog/574854) 

Got an error message at `/company/citymobil/blog/574854`:
```javascript
Error: undefined:1:9: property missing ':'

    at Na (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:38152)
    at div
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2029169
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2011678
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:441583)
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:670973
    at div
    at div
    at div
    at Rr (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:77307)
    at div
    at div
    at vr (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:76305)
    at Li (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:107248)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:9720)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:11768)
    at gu (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:365449)
    at div
    at div
    at c (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:88157)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2136149)
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2028790
    at Eh (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:434442)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:6323)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:23068)
    at u (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:20135)
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2138254
```

**Comment by jarvis394** [comment] 2021-08-31 06:56
Duplicate of #125

**Closed by jarvis394** 2021-08-31 06:56 UTC
