### ISSUE TITLE
Encountered an error (TypeError: First argument must be a string)

### ISSUE THREAD

**Issue by kostyatab** [jarvis394/habra#123] opened 2021-08-30 11:14 UTC
### Describe the problem:
Got an error message at `/user/Arnak/articles/p/1`:
```javascript
TypeError: First argument must be a string

    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:452626)
    at Io (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:171050)
    at ul
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2062015
    at https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2011678
    at div
    at div
    at vr (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:76305)
    at Rp (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:343792)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:9720)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:11768)
    at gu (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:365449)
    at div
    at div
    at c (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:88157)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2136149)
    at t.a (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2028790)
    at Eh (https://habra.vercel.app/static/js/main.78454288.chunk.js:1:434442)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:6323)
    at t (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:23068)
    at u (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:20135)
    at t.a (https://habra.vercel.app/static/js/2.b675164f.chunk.js:2:2138254)
```

**Comment by jarvis394** [comment] 2021-08-30 11:49
Duplicate of #121

**Closed by jarvis394** 2021-08-30 11:49 UTC
